# Last LTS version of node
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Copy the file from your host to your current location
COPY package*.json ./

# Run the command inside your image filesystem
RUN npm install

# Copy the rest of your app's source code from your host to your image filesystem
COPY . .

# Inform Docker that the container is listening on the specified port at runtime.
EXPOSE 8080

# Run a health check to test that the container is working as expected.
HEALTHCHECK --interval=30s --timeout=10s --retries=3 CMD curl -f http://localhost:8080/ || exit 1

# Run the specified command within the container.
CMD [ "npx", "expo", "start" ] 