[functions]                      # omit if you kept the default folder
  directory = "netlify/functions"

[[redirects]]
  from = "/api/llama/*"
  to   = "/.netlify/functions/llama/:splat"
  status = 200          # ← rewrite, not redirect
  force  = true         # (optional) skip other rules