name: Run Tests

on:
  push:
    branches:
      - CI/CD  
      - MoonshotV2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12  # Use your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r MaGestionProMoonshot/requirements.txt

    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: pytest MaGestionProMoonshot/tests/